builders:
  generate_module:
    import: "package:ayanami/builder.dart"
    builder_factories:
      - moduleBuilder
    build_extensions:
      .module.dart: 
        - .m.dart
    build_to: source
    auto_apply: root_package
    runs_before:
      - reflectable|reflectable
  singleton:
    import: "package:ayanami/singleton_builder.dart"
    builder_factories:
      - singletonBuilder
    build_extensions:
      .dart: 
        - .singleton.dart
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        exclude:
        - lib/**.dart
        include:
        - lib/main.dart
