name: ayanami
description: State management with rxdart
homepage: https://github.com/LeetCode-OpenSource/ayanami.dart
author: LongYinan <lynweklm@gmail.com>

version: 0.0.8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^0.34.3

  angel_container: ^1.0.4

  angel_container_generator: ^1.0.1

  build: ^1.1.0

  build_runner: ^1.2.3

  rxdart: ^0.22.0

  source_gen: ^0.9.4

  meta: ^1.1.6
